sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
cache:
  directories:
    - $HOME/.stack

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
    --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup
script:
  - stack test --pedantic
  - stack sdist
after_success:
  - >
    test $TRAVIS_TAG &&
    mkdir -p ~/.stack/upload &&
    echo "{
      \"username\": \"$HACKAGE_USERNAME\",
      \"password\": \"$HACKAGE_PASSWORD\"
    }" > ~/.stack/upload/credentials.json &&
    stack upload .
