name: lackey
version: 0.4.5

category: Web
description: Lackey generates Ruby clients from Servant APIs.
extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml
github: tfausak/lackey
license: MIT
maintainer: Taylor Fausak
synopsis: Generate Ruby clients from Servant APIs.

dependencies:
  - base >= 4.8 && < 4.11
  - servant >= 0.8 && < 0.13
  - servant-foreign >= 0.8 && < 0.11
  - text >= 1.2 && < 1.3
ghc-options:
  - -Wall

library:
  source-dirs: library

tests:
  test:
    dependencies:
      - lackey
      - hspec >= 2.4.4 && < 2.5
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    source-dirs: tests
    main: Main.hs
