category: Web
description: Lackey generates Ruby clients from Servant APIs.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: tfausak/lackey
library:
  dependencies:
  - base >=4.8 && <4.10
  - servant >=0.5 && <0.8
  - servant-foreign >=0.5 && <0.8
  - text >=1.2 && <1.3
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: lackey
synopsis: Generate Ruby clients from Servant APIs.
tests:
  lackey-test-suite:
    dependencies:
    - base
    - lackey
    - servant
    - tasty >=0.11 && <0.12
    - tasty-hspec >=1.1 && <1.2
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    source-dirs: test-suite
    main: Main.hs
version: '0.3.1'
