name: lackey
version: 1.0.7

category: Web
description: Lackey generates Ruby clients from Servant APIs.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/lackey
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Generate Ruby clients from Servant APIs.

dependencies:
  base: '>= 4.9.0 && < 4.13'
  servant: '>= 0.8.1 && < 0.16'
  servant-foreign: '>= 0.8.1 && < 0.16'
  text: '>= 1.2.2 && < 1.3'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

tests:
  test:
    dependencies:
      hspec: '>= 2.2.3 && < 2.8'
      lackey: -any
    ghc-options:
      - -rtsopts
      - -threaded
    source-dirs: tests
    main: Main.hs
